name : "01 - Building blocks"
on:
  workflow_dispatch

jobs: 
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Say hello"
        run : echo "Hello World"
        
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name : "Successful step"
        run : |                 # multiline script - use "" | ""
          echo "I will succeed"
          exit 0

      - name: "Say goodbye"
        run : echo "Bye World"