name : "Practical exercise 1"
on : 
  - push
  - workflow_dispatch

jobs: 
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: "Say hello"
        run : echo "Hello World"
        
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name : "Failed step"
        run : |                 # multiline script - use "" | ""
          echo "I will fail"
          exit 1

      - name: "Say goodbye"
        run : echo "Bye World"