name: 04 - Using Actions
on: push
jobs: 
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: 04-using-actions/my-app
        # checkout code from repository
        # install deps of the project
        # run automated tests
        steps:
            -   name: Checkout code
                uses: actions/checkout@v7

            -   name: Setup Node.js
                uses: actions/setup-node@v7
                with:
                    node-version: 24
    
            -   name: Install dependencies
                run: npm ci
                # working-directory: 04-using-actions/my-app

            -   name: Run tests
                run: npm test
                # working-directory: 04-using-actions/my-app