name: 04 - Using Actions
on: push
jobs: 
    build:
        runs-on: ubuntu-latest
        # checkout code from repository
        # install deps of the project
        # run automated tests
        steps:
            -   name: Checkout code
                uses: actions/checkout@v7

            -   name: Printing folders
                run: ls
            