name : 07 - Using Expressions

run-name : 07 - Using Expressions | Expression DEBUG - ${{ inputs.debug }}

on: 
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[debug] Print start-up data"
              run: |
                echo "Debug: ${{ inputs.debug }}"

            - name: "print debug information"
              if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug == true }}
              run: |
                echo "Triggered by: ${{ github.event_name }}"
                echo "Branch: ${{ github.ref }}"
                echo "Commit SHA: ${{ github.sha }}"
                echo "Runner OS: ${{ runner.os }}"

            - name: "print non-debug information"
              if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug == false }}
              run: |
                echo "Debug mode is off. No additional information will be displayed."