name: 11 - Working with Input

on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: 'Skip deployment and only print build output'
                type: boolean
                default: false
            target:
                type: environment
                description: 'Which environment the workflow will target'
                required: true
            tag:
                type: choice
                description: 'Release from which to build and deploy'
                options:
                    - v1
                    - v2
                    - v3
                default: v3
        
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building from tag ${{ inputs.tag }}"

    deploy:
        needs: build
        if: ${{ inputs['dry-run'] == 'false' }}
        runs-on: ubuntu-latest
        environment: ${{ inputs.target }}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{ inputs.target }}"